### ISSUE TITLE
Is it work with 3.3v?

### ISSUE THREAD

**Issue by alantang888** [bradsprojects/DigiPixel#21]
I bought DigiPixel many years ago from kickstarter. But didn’t play much with it. Now I just bought a Raspberry Pico, and I want to try DigiPixel with it. But Arduino is 5v and Pico is 3.3v on IO pin. So I wonder can it still work. I can’t find any docs mention what voltage is DigiPixel’s high level input voltage.

Thanks a lot.

**Comment by bradsprojects** [comment]
Sorry for the delayed reply. You should be fine with 3.3V logic levels for the IO pins - however the main concern will be the LED's may not be bright enough.

**Comment by alantang888** [comment]
Thanks Brad
